# Allwinner H618 quad core 2/4GB RAM 8GB eMMC SoC WiFi\Bt HDMI SPI USB-C
BOARD_NAME="BananaPi M4 Berry"
BOARD_VENDOR="sinovoip"
BOARDFAMILY="sun50iw9-bpi"
BOARD_MAINTAINER="The-going"
INTRODUCED="2023"
BOOTCONFIG="bananapi_m4_berry_defconfig"

BOOTPATCHDIR="v2025-sunxi"
BOOTBRANCH_BOARD="tag:v2025.04"

OVERLAY_PREFIX="sun50i-h616"
BOOT_FDT_FILE="sun50i-h618-bananapi-m4-berry.dtb"
BOOT_LOGO="desktop"
KERNEL_TARGET="current,edge"
KERNEL_TEST_TARGET="current"

PACKAGE_LIST_BOARD="rfkill bluetooth bluez bluez-tools hostapd"

# shellcheck source=config/boards/include/bananapi-h618-common.inc
source "${SRC}/config/boards/include/bananapi-h618-common.inc"

function post_family_tweaks_bsp__bananapi_module_conf() {

	mkdir -p "${destination}"/etc/udev/rules.d/
	mkdir -p "${destination}"/usr/local/bin/
	mkdir -p "${destination}"/usr/local/sbin/

	install -m 0644 "${SRC}"/packages/bsp/bananapi-m4berry/99-bananapi-m4berry-io.rules \
			"${destination}"/etc/udev/rules.d/99-bananapi-m4berry-io.rules
	install -m 0755 "${SRC}"/packages/bsp/bananapi-m4berry/bpi-m4berry-hw-info \
			"${destination}"/usr/local/bin/bpi-m4berry-hw-info
	install -m 0755 "${SRC}"/packages/bsp/bananapi-m4berry/bpi-m4berry-io-compat-install \
			"${destination}"/usr/local/sbin/bpi-m4berry-io-compat-install

}
