# Allwinner A64 quad core 2GB RAM SoC WiFi/BT eMMC GBE
BOARD_NAME="Banana Pi M64"
BOARD_VENDOR="sinovoip"
BOARDFAMILY="sun50iw1"
BOARD_MAINTAINER="devdotnetorg"
INTRODUCED="2016"
BOOTCONFIG_DEFAULT="sun50iw1p1_config"
BOOTCONFIG="bananapi_m64_defconfig"
BOOT_FDT_FILE="allwinner/sun50i-a64-bananapi-m64.dtb"
OVERLAY_PREFIX="sun50i-a64"
PACKAGE_LIST_BOARD="rfkill bluetooth bluez bluez-tools iw ethtool usbutils alsa-utils smartmontools gpiod i2c-tools python3-libgpiod python3-spidev v4l-utils"
KERNEL_TARGET="current,edge,legacy"
KERNEL_TEST_TARGET="current"
CRUSTCONFIG="a64_defconfig"

# Current 候選固定完整啟動鏈與 AP6212 韌體來源；保留共用 648 MHz DRAM 修補。
KERNELSOURCE_BOARD="https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git"
KERNELBRANCH_BOARD="commit:1f99e9ab748fc5c32120de9c4eca31abfe54a4d5"
BOOTBRANCH_BOARD="commit:866ca972d6c3cabeaf6dbac431e8e08bb30b3c8e"
ATFSOURCE_BOARD="https://github.com/ARM-software/arm-trusted-firmware"
ATFBRANCH_BOARD="commit:c2a0e7080d64d69940be4ad0ff6578501f3cbf9e"
CRUSTSOURCE_BOARD="https://github.com/crust-firmware/crust"
CRUSTBRANCH_BOARD="commit:ffe9f1ac9c675e6e67db9084bd19fbdeffd8e162"
ARMBIAN_FIRMWARE_GIT_REF_BOARD="commit:f50a2a21bcdb77a562b3976930c5c6b521a1df08"

function post_family_config_branch_current__bananapim64_pin_sources() {
	declare -g KERNELSOURCE="${KERNELSOURCE_BOARD}"
	declare -g KERNELBRANCH="${KERNELBRANCH_BOARD}"
	declare -g BOOTBRANCH="${BOOTBRANCH_BOARD}"
	declare -g ATFSOURCE="${ATFSOURCE_BOARD}"
	declare -g ATFBRANCH="${ATFBRANCH_BOARD}"
	declare -g CRUSTSOURCE="${CRUSTSOURCE_BOARD}"
	declare -g CRUSTBRANCH="${CRUSTBRANCH_BOARD}"
	declare -g ARMBIAN_FIRMWARE_GIT_REF="${ARMBIAN_FIRMWARE_GIT_REF_BOARD}"
}
