# Allwinner H3 quad core 1Gb RAM SoC Wifi GBE
BOARD_NAME="Banana Pi M2+"
BOARD_VENDOR="sinovoip"
BOARDFAMILY="sun8i"
BOARD_MAINTAINER="leggewie"
INTRODUCED="2016"
BOOTCONFIG="bananapi_m2_plus_h3_defconfig"
DEFAULT_OVERLAYS="analog-codec"
PACKAGE_LIST_BOARD="rfkill bluetooth bluez bluez-tools gpiod i2c-tools python3-libgpiod python3-spidev v4l-utils"
MODULES_CURRENT="g_serial"
MODULES_LEGACY="g_serial"
SERIALCON="ttyS0,ttyGS0"
KERNEL_TARGET="current,edge,legacy"
KERNEL_TEST_TARGET="current"
