# Renesas RZ/V2N SoC Quad-core Vision AI MPU with DRP-AI3 Accelerator
BOARD_NAME="Banana Pi AI2N"
BOARD_VENDOR="sinovoip"
BOARDFAMILY="renesas-rzv2n-bpi"
BOARD_MAINTAINER="BPI-SINOVOIP"
INTRODUCED="2026"
KERNEL_TARGET="legacy"
KERNEL_TEST_TARGET="legacy"
FULL_DESKTOP="yes"
SERIALCON="ttySC0"
BOOT_LOGO="desktop"

#SKIP_BOOTSPLASH="yes" # Skip boot splash patch, conflicts with CONFIG_VT=yes

BOOTCONFIG="bananapi_ai2n_defconfig"
LINUXCONFIG="linux-renesas-rzv2n-bpi-ai2n"
BOOT_FDT_FILE="renesas/bananapi-ai2n.dtb"

BOOTENV_FILE="renesas-bpi.txt"
BOOTSCRIPT="boot-renesas-rzv2n-bpi.cmd:boot.cmd"

OVERLAY_PREFIX="bpi-ai2n"
DEFAULT_OVERLAYS=""

MODULES=""
PACKAGE_LIST_BOARD="alsa-utils ethtool gpiod i2c-tools iperf3 iproute2 iw pciutils python3-libgpiod python3-spidev rfkill spi-tools usbutils v4l-utils"
ARMBIAN_FIRMWARE_GIT_SOURCE_BOARD="https://github.com/armbian/firmware"
ARMBIAN_FIRMWARE_GIT_REF_BOARD="commit:f50a2a21bcdb77a562b3976930c5c6b521a1df08"

function extension_prepare_config__bpi_ai2n_pin_firmware() {
	declare -g ARMBIAN_FIRMWARE_GIT_SOURCE="${ARMBIAN_FIRMWARE_GIT_SOURCE_BOARD}"
	declare -g ARMBIAN_FIRMWARE_GIT_REF="${ARMBIAN_FIRMWARE_GIT_REF_BOARD}"
}

function image_specific_armbian_env_ready__rzv2n_bpi_bootscript() {
	display_alert "$BOARD" "Updating boot script and env" "info"

	sed -i 's/board=/board=bpi-ai2n/g' "${SDCARD}"/boot/armbianEnv.txt
}
